#!/usr/bin/env python3
"""AI Transformation Request Portfolio.

Takes an intake log of AI/transformation requests and produces a ranked portfolio
with a one-line decision and a short brief per request. It applies the same gates
every time, so the ranking does not depend on who asked:

  Gate 0  Forbidden zone  - legal/policy hard stops are removed before scoring
  Gate 1  Readiness zone  - data readiness x process readiness (zones 1-4)
  Gate 2  Value x readiness quadrant, then adjustment factors:
          change capacity, reusable pattern value, reversibility

Usage:
  python prioritize.py --intake sample/intake.csv --out out/portfolio.md
Standard library only. Sample requests are fictional.
"""
import argparse, csv
from pathlib import Path


def zone(r):
    if r["forbidden"] == "yes":
        return 5, "Forbidden: excluded before scoring"
    d, p = int(r["data_ready"]) >= 3, int(r["process_ready"]) >= 3
    return {(True, True): (1, "Ready to evaluate"), (False, True): (2, "Fix data access & quality first"),
            (True, False): (3, "Stabilize the process first"), (False, False): (4, "Not ready")}[(d, p)]


def quadrant(v, rd):
    if v >= 4 and rd >= 4: return "Prioritize"
    if v >= 4: return "Invest & schedule"
    if rd >= 4: return "Pilot with caution"
    return "Decline for now"


def score(r):
    v, rd = int(r["value"]), int(r["readiness"])
    s, why = v * rd, []
    if r["change_capacity"] == "low": s -= 4; why.append("team has low change capacity (-4)")
    if r["reusable_pattern"] == "yes": s += 2; why.append("creates a reusable pattern (+2)")
    if r["reversible"] == "no":
        s -= 3; why.append("errors are hard to reverse (-3)")
        if r["data_class"] == "red": why.append("red data + irreversible: human approval on every output")
    return s, why


def annual_hours(r):
    return float(r["volume_per_month"]) * float(r["minutes_saved_per_item"]) / 60 * 12


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--intake", required=True)
    ap.add_argument("--out", default="out/portfolio.md")
    a = ap.parse_args()
    rows = list(csv.DictReader(open(a.intake, newline="", encoding="utf-8")))
    scored = []
    for r in rows:
        z, zl = zone(r)
        hrs = annual_hours(r); gross = hrs * float(r["hourly_cost"])
        if z != 1:
            decision = "Excluded" if z == 5 else f"Not yet: {zl}"
            scored.append(dict(r=r, z=z, zl=zl, s=None, q="-", why=[], hrs=hrs, gross=gross, decision=decision))
            continue
        s, why = score(r)
        q = quadrant(int(r["value"]), int(r["readiness"]))
        decision = {"Prioritize": "Build business case now", "Invest & schedule": "Fix readiness, re-score in 90 days",
                    "Pilot with caution": "Small pilot if capacity allows", "Decline for now": "Decline; revisit next quarter"}[q]
        scored.append(dict(r=r, z=z, zl=zl, s=s, q=q, why=why, hrs=hrs, gross=gross, decision=decision))
    ranked = sorted([x for x in scored if x["s"] is not None], key=lambda x: (-x["s"], -x["gross"]))
    parked = [x for x in scored if x["s"] is None]

    L = ["# AI transformation request portfolio", "", "_Generated by prioritize.py. Every request goes through the same gates, so the ranking "
         "does not depend on who asked._", "",
         "## How to read this", "",
         "### Value and Ready (scored 1-5 by the requester, checked by the reviewer)",
         "| Score | Value: how much it moves the business | Ready: how ready the data and process are |",
         "|---|---|---|",
         "| 5 | Shifts a core KPI (for example cost to serve -20%) | Clean, structured, access-controlled data; stable, documented process |",
         "| 4 | 10-20% gain on a key process | Minor cleanup needed |",
         "| 3 | 5-10% productivity gain | A defined cleanup project is needed first |",
         "| 2 | Under 5%; mostly convenience | Data largely unstructured; process varies by person |",
         "| 1 | Negligible | Data quality unknown; no agreed process |",
         "",
         "### Quadrant (from Value and Ready)",
         "| Quadrant | Rule | What it means |",
         "|---|---|---|",
         "| Prioritize | Value 4-5 and Ready 4-5 | High impact and ready now: build the business case |",
         "| Invest & schedule | Value 4-5, Ready 1-3 | Worth doing, but fix data or process first; re-score in 90 days |",
         "| Pilot with caution | Value 1-3, Ready 4-5 | Easy to start but modest payoff: small pilot only if the team has capacity |",
         "| Decline for now | Value 1-3 and Ready 1-3 | Low impact and not ready: revisit next quarter |",
         "",
         "### Score and rank",
         "- **Score = Value x Ready** (maximum 25), then adjusted: **+2** if it creates a reusable pattern other teams can copy; "
         "**-4** if the team has low capacity for change; **-3** if mistakes are hard to undo.",
         "- Requests are **ranked by score**; a tie goes to the higher gross value.",
         "- Before scoring, two gates remove requests: the **forbidden zone** (a legal or policy rule reserves the decision for a human) "
         "and the **readiness zone** (data readiness or process readiness below 3 means \"fix this first\").",
         "- **Data class:** green = public, amber = internal, red = personal, financial, legal or regulated. "
         "Red data plus mistakes that are hard to undo means a human approves every output.",
         "",
         "### Hours and gross value",
         "- **Hours/yr = volume per month x minutes saved per item / 60 x 12.** Volume comes from the team's system (tickets, quotes, "
         "contracts per month); minutes saved come from a short time study of the task today versus with AI.",
         "- **Loaded cost** is the hourly cost of the people doing the work: salary plus benefits and overhead, from Finance.",
         "- **Gross value/yr = Hours/yr x loaded cost.** It is gross because not every saved hour becomes money; "
         "prototype 03 applies a realization factor to get the value that actually reaches the P&L.",
         "",
         "## Ranked portfolio", "",
         "| Rank | ID | Request | Function | Value | Ready | Score | Quadrant | Hours/yr | Gross value/yr | Decision |",
         "|---|---|---|---|---|---|---|---|---|---|---|"]
    for i, x in enumerate(ranked, 1):
        r = x["r"]
        L.append(f"| {i} | {r['id']} | {r['title']} | {r['function']} | {r['value']} | {r['readiness']} | {x['s']} | {x['q']} | "
                 f"{x['hrs']:,.0f} | ${x['gross']:,.0f} | {x['decision']} |")
    L += ["", "## Not scored", "| ID | Request | Function | Zone | Reason |", "|---|---|---|---|---|"]
    for x in parked:
        r = x["r"]; L.append(f"| {r['id']} | {r['title']} | {r['function']} | {x['z']} | {x['zl']} |")
    L += ["", "## Decision briefs"]
    for i, x in enumerate(ranked, 1):
        r = x["r"]
        L += ["", f"### {i}. {r['title']} ({r['id']}, {r['function']})",
              f"- **Problem:** {r['problem']}",
              f"- **Requested by:** {r['requester']}",
              f"- **Size of prize:** {float(r['volume_per_month']):,.0f} items/month x {float(r['minutes_saved_per_item']):g} min saved / 60 x 12 = "
              f"**{x['hrs']:,.0f} hours/yr** x ${float(r['hourly_cost']):g}/h loaded cost = **${x['gross']:,.0f} gross/yr** (before realization)",
              f"- **Why Value {r['value']}, Ready {r['readiness']}:** data readiness {r['data_ready']}/5, process readiness {r['process_ready']}/5, "
              f"data class {r['data_class']}, change capacity {r['change_capacity']}",
              f"- **Scoring:** value {r['value']} x readiness {r['readiness']} = {int(r['value']) * int(r['readiness'])}; "
              + ("; ".join(x["why"]) if x["why"] else "no adjustments") + f" -> **{x['s']}**",
              f"- **Decision:** {x['decision']}"]
    Path(a.out).parent.mkdir(parents=True, exist_ok=True)
    Path(a.out).write_text("\n".join(L) + "\n", encoding="utf-8")
    print(f"[ok] {len(ranked)} scored, {len(parked)} parked -> {a.out}")
    for i, x in enumerate(ranked[:3], 1):
        print(f"  {i}. {x['r']['title']} ({x['q']}, score {x['s']})")


if __name__ == "__main__":
    main()
