#!/usr/bin/env python3
"""MBR Assistant: turn raw partner activity data into a monthly business review draft.

Workflow it rebuilds: every month a partner marketing manager pulled activity data,
built KPI tables by hand and wrote a business review per partner. This script does
steps 1-3 deterministically (clean, calculate, analyze) so the numbers are always
checked, then either writes a draft itself or hands a structured prompt to an LLM
for step 4 (narrative). A human reviews every draft before it is shared.

Usage:
  python mbr.py --data sample/partner_activity_2026-05.csv --out out/
  python mbr.py --data sample/partner_activity_2026-05.csv --partner "Cedar CX"
  # Optional LLM narrative (Anthropic Messages API):
  ANTHROPIC_API_KEY=... MBR_MODEL=<model-id> python mbr.py --data ... --llm

Standard library only. All sample data is fictional.
"""
import argparse, csv, json, os, sys, urllib.request
from collections import defaultdict
from pathlib import Path

COST_PER_OPP_TARGET = 2000  # JMP target: MDF per co-sell opportunity
NUM = ["mdf_spent", "leads", "opportunities", "pipeline_usd", "marketplace_deals"]


def money(x):
    return "$" + f"{x:,.0f}"


def load(path):
    rows, issues = [], []
    with open(path, newline="", encoding="utf-8") as f:
        for i, r in enumerate(csv.DictReader(f), start=2):
            clean = {k.strip(): (v or "").strip() for k, v in r.items()}
            for k in NUM:  # step 1: clean - tolerate "$1,200", blanks
                raw = clean.get(k, "").replace("$", "").replace(",", "")
                try:
                    clean[k] = float(raw) if raw else 0.0
                except ValueError:
                    issues.append(f"line {i}: '{k}' is not a number ({clean.get(k)!r}); set to 0")
                    clean[k] = 0.0
            if not clean.get("partner"):
                issues.append(f"line {i}: missing partner name; row skipped")
                continue
            rows.append(clean)
    return rows, issues


def analyze(rows):
    t = {k: sum(r[k] for r in rows) for k in NUM}  # step 2: calculate
    funded = [r for r in rows if r["mdf_spent"] > 0]
    funded_opps = sum(r["opportunities"] for r in funded)
    cpo = (t["mdf_spent"] / funded_opps) if funded_opps else None
    ranked = sorted(funded, key=lambda r: r["pipeline_usd"] / r["mdf_spent"], reverse=True)
    best = next((r for r in ranked if r["pipeline_usd"] > 0), None)  # step 3: analyze
    with_opps = [r for r in ranked if r["opportunities"] > 0]
    worst = with_opps[-1] if len(with_opps) > 1 else None
    no_opp = [r for r in funded if r["opportunities"] == 0]
    free_wins = [r for r in rows if r["mdf_spent"] == 0 and r["opportunities"] > 0]
    low_conv = [r for r in funded if r["leads"] >= 40 and 0 < r["opportunities"] / r["leads"] < 0.03]
    return dict(totals=t, cpo=cpo, best=best, worst=worst if worst is not best else None,
                no_opp=no_opp, free_wins=free_wins, low_conv=low_conv, n=len(rows))


def draft(partner, month, a):
    t, lines = a["totals"], []
    cpo_txt = "n/a" if a["cpo"] is None else money(a["cpo"])
    on_target = a["cpo"] is not None and a["cpo"] <= COST_PER_OPP_TARGET
    lines += [f"# Monthly business review: {partner} ({month})", "",
              "_Draft generated by MBR Assistant. Numbers are calculated, not generated. Review before sharing._", "",
              "## Summary",
              f"{partner} ran {a['n']} activities, generating {int(t['leads'])} leads, {int(t['opportunities'])} co-sell "
              f"opportunities and {money(t['pipeline_usd'])} in pipeline from {money(t['mdf_spent'])} of MDF. "
              + (f"MDF per opportunity was {cpo_txt}, {'within' if on_target else 'above'} the {money(COST_PER_OPP_TARGET)} target." if a["cpo"] else ""),
              "", "## KPIs", "| Metric | Value |", "|---|---|",
              f"| Leads | {int(t['leads'])} |", f"| Co-sell opportunities | {int(t['opportunities'])} |",
              f"| Pipeline | {money(t['pipeline_usd'])} |", f"| MDF spent | {money(t['mdf_spent'])} |",
              f"| MDF per opportunity | {cpo_txt} |", f"| Marketplace deals | {int(t['marketplace_deals'])} |", "",
              "## What worked"]
    if a["best"]:
        b = a["best"]
        lines.append(f"- **{b['activity']}**: {money(b['pipeline_usd'])} pipeline from {money(b['mdf_spent'])} MDF "
                     f"({b['pipeline_usd'] / b['mdf_spent']:.0f}x the spend).")
    for r in a["free_wins"]:
        lines.append(f"- **{r['activity']}** produced {int(r['opportunities'])} opportunities at no MDF cost.")
    if t["marketplace_deals"]:
        n = int(t["marketplace_deals"]); lines.append(f"- {n} Marketplace transaction{'s' if n != 1 else ''} closed.")
    lines += ["", "## What needs attention"]
    issues = []
    for r in a["no_opp"]:
        issues.append(f"- **{r['activity']}** spent {money(r['mdf_spent'])} with no opportunities yet.")
    if a["worst"]:
        w = a["worst"]
        issues.append(f"- **{w['activity']}** had the lowest return: {money(w['pipeline_usd'])} from {money(w['mdf_spent'])}.")
    for r in a["low_conv"]:
        issues.append(f"- **{r['activity']}** brought {int(r['leads'])} leads but few converted; check lead quality and follow-up.")
    if a["cpo"] and not on_target:
        issues.append(f"- MDF per opportunity ({cpo_txt}) is above target.")
    lines += issues or ["- No major issues this month."]
    lines += ["", "## Suggested next steps (for discussion)"]
    if a["best"]:
        lines.append(f"- Repeat the format of {a['best']['activity']} next quarter; shift budget toward it.")
    if a["no_opp"]:
        lines.append(f"- Pause or rework {a['no_opp'][0]['activity']} before further spend.")
    if t["leads"]:
        lines.append(f"- Follow up all {int(t['leads'])} leads within 10 business days; register qualified ones for co-sell.")
    if not t["marketplace_deals"]:
        lines.append("- Prepare a private offer for the two most advanced deals.")
    return "\n".join(lines) + "\n"


PROMPT = Path(__file__).with_name("prompt_template.md")


def build_prompt(partner, month, a, rows):
    table = "\n".join(f"| {r['date']} | {r['activity']} | {r['type']} | {money(r['mdf_spent'])} | {int(r['leads'])} | "
                      f"{int(r['opportunities'])} | {money(r['pipeline_usd'])} |" for r in rows)
    kpis = json.dumps({k: (round(v, 2) if isinstance(v, float) else v) for k, v in a["totals"].items()}
                      | {"mdf_per_opportunity": round(a["cpo"], 2) if a["cpo"] else None}, indent=2)
    return PROMPT.read_text(encoding="utf-8").format(partner=partner, month=month, kpis=kpis, table=table,
                                                     target=COST_PER_OPP_TARGET)


def call_llm(prompt):
    key, model = os.environ.get("ANTHROPIC_API_KEY"), os.environ.get("MBR_MODEL")
    if not key or not model:
        sys.exit("Set ANTHROPIC_API_KEY and MBR_MODEL to use --llm (see README).")
    req = urllib.request.Request("https://api.anthropic.com/v1/messages", method="POST",
                                 headers={"x-api-key": key, "anthropic-version": "2023-06-01", "content-type": "application/json"},
                                 data=json.dumps({"model": model, "max_tokens": 1200,
                                                  "messages": [{"role": "user", "content": prompt}]}).encode())
    with urllib.request.urlopen(req, timeout=60) as resp:
        body = json.load(resp)
    return "".join(b.get("text", "") for b in body.get("content", []))


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--data", required=True)
    ap.add_argument("--partner", help="one partner (default: all)")
    ap.add_argument("--month", default="May 2026")
    ap.add_argument("--out", default="out")
    ap.add_argument("--llm", action="store_true", help="write the narrative with an LLM instead of the template")
    args = ap.parse_args()

    rows, issues = load(args.data)
    by_partner = defaultdict(list)
    for r in rows:
        by_partner[r["partner"]].append(r)
    partners = [args.partner] if args.partner else sorted(by_partner)
    out = Path(args.out); out.mkdir(parents=True, exist_ok=True)
    for p in partners:
        if p not in by_partner:
            sys.exit(f"Partner {p!r} not found. Available: {', '.join(sorted(by_partner))}")
        a = analyze(by_partner[p])
        slug = p.lower().replace(" ", "-")
        prompt = build_prompt(p, args.month, a, by_partner[p])
        (out / f"{slug}_prompt.md").write_text(prompt, encoding="utf-8")
        text = call_llm(prompt) if args.llm else draft(p, args.month, a)
        (out / f"{slug}_mbr.md").write_text(text, encoding="utf-8")
        print(f"[ok] {p}: {int(a['totals']['opportunities'])} opps, {money(a['totals']['pipeline_usd'])} pipeline -> {out / (slug + '_mbr.md')}")
    for msg in issues:
        print("[data]", msg)


if __name__ == "__main__":
    main()
