#!/usr/bin/env python3
"""Transformation intake prioritizer.

Takes an intake log of AI/transformation requests and produces a ranked portfolio
with a one-line decision and a short brief per request. It applies the same gates
every time, so the ranking does not depend on who asked:

  Gate 0  Forbidden zone  - legal/policy hard stops are removed before scoring
  Gate 1  Readiness zone  - data readiness x process readiness (zones 1-4)
  Gate 2  Value x readiness quadrant, then adjustment factors:
          change capacity, reusable pattern value, reversibility

Usage:
  python prioritize.py --intake sample/intake.csv --out out/portfolio.md
Standard library only. Sample requests are fictional.
"""
import argparse, csv
from pathlib import Path


def zone(r):
    if r["forbidden"] == "yes":
        return 5, "Forbidden: excluded before scoring"
    d, p = int(r["data_ready"]) >= 3, int(r["process_ready"]) >= 3
    return {(True, True): (1, "Ready to evaluate"), (False, True): (2, "Fix data access & quality first"),
            (True, False): (3, "Stabilize the process first"), (False, False): (4, "Not ready")}[(d, p)]


def quadrant(v, rd):
    if v >= 4 and rd >= 4: return "Prioritize"
    if v >= 4: return "Invest & schedule"
    if rd >= 4: return "Pilot with caution"
    return "Decline for now"


def score(r):
    v, rd = int(r["value"]), int(r["readiness"])
    s, why = v * rd, []
    if r["change_capacity"] == "low": s -= 4; why.append("team has low change capacity (-4)")
    if r["reusable_pattern"] == "yes": s += 2; why.append("creates a reusable pattern (+2)")
    if r["reversible"] == "no":
        s -= 3; why.append("errors are hard to reverse (-3)")
        if r["data_class"] == "red": why.append("red data + irreversible: human approval on every output")
    return s, why


def annual_hours(r):
    return float(r["volume_per_month"]) * float(r["minutes_saved_per_item"]) / 60 * 12


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--intake", required=True)
    ap.add_argument("--out", default="out/portfolio.md")
    a = ap.parse_args()
    rows = list(csv.DictReader(open(a.intake, newline="", encoding="utf-8")))
    scored = []
    for r in rows:
        z, zl = zone(r)
        hrs = annual_hours(r); gross = hrs * float(r["hourly_cost"])
        if z != 1:
            decision = "Excluded" if z == 5 else f"Not yet: {zl}"
            scored.append(dict(r=r, z=z, zl=zl, s=None, q="-", why=[], hrs=hrs, gross=gross, decision=decision))
            continue
        s, why = score(r)
        q = quadrant(int(r["value"]), int(r["readiness"]))
        decision = {"Prioritize": "Build business case now", "Invest & schedule": "Fix readiness, re-score in 90 days",
                    "Pilot with caution": "Small pilot if capacity allows", "Decline for now": "Decline; revisit next quarter"}[q]
        scored.append(dict(r=r, z=z, zl=zl, s=s, q=q, why=why, hrs=hrs, gross=gross, decision=decision))
    ranked = sorted([x for x in scored if x["s"] is not None], key=lambda x: (-x["s"], -x["gross"]))
    parked = [x for x in scored if x["s"] is None]

    L = ["# Transformation portfolio", "", "_Generated by prioritize.py. Scores use fixed 1-5 rubrics; gross value = hours x loaded cost "
         "before any realization factor._", "",
         "| Rank | ID | Request | Function | Value | Ready | Score | Quadrant | Hours/yr | Gross value/yr | Decision |",
         "|---|---|---|---|---|---|---|---|---|---|---|"]
    for i, x in enumerate(ranked, 1):
        r = x["r"]
        L.append(f"| {i} | {r['id']} | {r['title']} | {r['function']} | {r['value']} | {r['readiness']} | {x['s']} | {x['q']} | "
                 f"{x['hrs']:,.0f} | ${x['gross']:,.0f} | {x['decision']} |")
    L += ["", "## Not scored", "| ID | Request | Function | Zone | Reason |", "|---|---|---|---|---|"]
    for x in parked:
        r = x["r"]; L.append(f"| {r['id']} | {r['title']} | {r['function']} | {x['z']} | {x['zl']} |")
    L += ["", "## Decision briefs"]
    for i, x in enumerate(ranked, 1):
        r = x["r"]
        L += ["", f"### {i}. {r['title']} ({r['id']}, {r['function']})",
              f"- **Problem:** {r['problem']}",
              f"- **Requested by:** {r['requester']} · **Data class:** {r['data_class']}",
              f"- **Size of prize:** {x['hrs']:,.0f} hours/yr, ${x['gross']:,.0f} gross before realization",
              f"- **Scoring:** value {r['value']} x readiness {r['readiness']} = {int(r['value']) * int(r['readiness'])}; "
              + ("; ".join(x["why"]) if x["why"] else "no adjustments") + f" -> **{x['s']}**",
              f"- **Decision:** {x['decision']}"]
    Path(a.out).parent.mkdir(parents=True, exist_ok=True)
    Path(a.out).write_text("\n".join(L) + "\n", encoding="utf-8")
    print(f"[ok] {len(ranked)} scored, {len(parked)} parked -> {a.out}")
    for i, x in enumerate(ranked[:3], 1):
        print(f"  {i}. {x['r']['title']} ({x['q']}, score {x['s']})")


if __name__ == "__main__":
    main()
